Kindergarten-liu/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :kindergartens
  root 'kindergartens#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Kindergarten-liu/app/models/kindergarten.rb
class Kindergarten < ApplicationRecord
  validates :title, presence: true
end

Kindergarten-liu/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Kindergarten-liu/app/controllers/kindergartens_controller.rb
class KindergartensController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]

  def index
    @kindergartens = Kindergarten.all
  end

  def show
    @kindergarten = Kindergarten.find(params[:id])
  end

  def edit
    @kindergarten = Kindergarten.find(params[:id])
  end

  def new
    @kindergarten = Kindergarten.new
  end

  def create
    @kindergarten = Kindergarten.new(kindergarten_params)
    if @kindergarten.save
      redirect_to kindergartens_path
    else
      render :new
    end
  end

  def update
    @kindergarten = Kindergarten.find(params[:id])
    if @kindergarten.update(kindergarten_params)
      redirect_to kindergartens_path, notice: "Update Success"
    else
      render :edit
    end
  end

  def destroy
    @kindergarten = Kindergarten.find(params[:id])
    @kindergarten.destroy
    flash[:alert] = "Kindergarten deleted"
    redirect_to kindergartens_path
  end

  private

  def kindergarten_params
    params.require(:kindergarten).permit(:title, :location, :price)
  end

end

Kindergarten-liu/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

Kindergarten-liu/app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

Kindergarten-liu/app/helpers/kindergartens_helper.rb
module KindergartensHelper
end

Kindergarten-liu/app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

Kindergarten-liu/app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Kindergarten-liu
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>Dezhengliu</a>
    </p>
</footer>

Kindergarten-liu/app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Job Listing </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                  <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登入", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

Kindergarten-liu/app/views/kindergartens/_form.html.erb
<%= simple_form_for @kindergarten do |f| %>
  <div class="form-kindergarten">
     <%= f.input :title, input_html: { class: "form-control"} %>
     <%= f.input :location, input_html: { class: "form-control"} %>
     <%= f.input :price, input_html: { class: "form-control"} %>
   </div>
 <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

Kindergarten-liu/app/views/kindergartens/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑幼儿园<h2>

    <hr>

  <%= render "form" %>

</div>

Kindergarten-liu/app/views/kindergartens/index.html.erb
<div class="col-md-12">
  <div class="kindergarten">
    <%= link_to("New kindergarten", new_kindergarten_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Location</td>
        <td>Price</td>
      </tr>
    </thead>
    <tbody>
      <% @kindergartens.each do |kindergarten| %>
        <tr>
          <td>#</td>
          <td><%= link_to(kindergarten.title, kindergarten_path(kindergarten)) %></td>
          <td><%= kindergarten.location %></td>
          <td><%= kindergarten.price %></td>
          <td>
              <%= link_to("Edit", edit_kindergarten_path(kindergarten), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", kindergarten_path(kindergarten),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

Kindergarten-liu/app/views/kindergartens/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增幼儿园<h2>

    <hr>

  <%= render "form" %>

</div>

Kindergarten-liu/app/views/kindergartens/show.html.erb
<div class="col-md-12">
  <div class="kindergarten">
    <%= link_to("Edit", edit_kindergarten_path(@kindergarten), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @kindergarten.title %></h2>
  <p><%= @kindergarten.location %></p>
  <p><%= @kindergarten.price %></p>
</div>

Kindergarten-liu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KindergartenLiu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

    <%= render "common/footer" %>

  </body>
</html>