job-listing3/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :admin do
    resources :jobs do
     member do
       post :publish
       post :hide
    end

    resources :resumes
  end
end
  resources :jobs do
    resources :resumes
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

job-listing3/app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
  validates :wage_upper_bound, presence: true
  validates :wage_lower_bound, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0}
  has_many :resumes
  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  scope :published, -> { where(is_hidden: false) }
  scope :recent, -> { order('created_at DESC')}
end

job-listing3/app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :user
  belongs_to :job

  mount_uploader :attachment, AttachmentUploader

  validates :content, presence: true
end

job-listing3/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :resumes

  def admin？
    is_admin
  end
end

job-listing3/app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show, :edit, :update, :destroy, :create ]
  before_action :require_is_admin
  layout "admin"

  def publish
    @job = Job.find(params[:id])
    @job.publish!
    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!
    redirect_to :back
  end


  def show
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to admin_jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end
end

job-listing3/app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin

  layout 'admin'

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order('created_at DESC')
  end
end

job-listing3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def require_is_admin
    if !current_user.admin？
       flash[:alert] = 'You are not admin'
       redirect_to root_path
    end
  end
end

job-listing3/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def show
    @job = Job.find(params[:id])
    if @job.is_hidden
      flash[:warning] = "This Job already archived"
      redirect_to root_path
    end
  end

  def index
    @jobs = case params[:order]
           when 'by_lower_bound'
             Job.published.order("wage_lower_bound DESC")
           when 'by_upper_bound'
             Job.published.order("wage_upper_bound DESC")
           else
             Job.published.recent
           end
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if@job.save
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end


  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_upper_bound, :wage_lower_bound, :contact_email, :is_hidden)
  end

end

job-listing3/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!
  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user

    if @resume.save
      flash[:notice] = "成功提交履历"
      redirect_to job_path(@job)
    else
      render :new
    end
  end

  private

  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end
end

job-listing3/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
     flash[:notice]="早安！你好！"
  end
end

job-listing3/app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

job-listing3/app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

job-listing3/app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

job-listing3/app/helpers/jobs_helper.rb
module JobsHelper
  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end
end

job-listing3/app/helpers/resumes_helper.rb
module ResumesHelper
end

job-listing3/app/views/admin/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for [:admin, @job ] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

job-listing3/app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to("Add a job", new_admin_job_path, :class => "btn btn-default" ) %>
</div>

<br> <br>

<table class="table table-boldered table-striped custab" >
  <thead>
    <tr>
        <td>
            职缺
        </td>

        <td>
          收到履历数量
        </td>
        <td>
            薪资下限
        </td>
        <td>
            薪资上限
        </td>
        <td>
            管理选项
        </td>
        <td>
            刊登时间
        </td>
    </tr>
</thead>

  <% @jobs.each do |job| %>
  <tr>
    <td>

      <%= render_job_status(job) %>

       <%= link_to(job.title, admin_job_path(job)) %>
    </td>
    <td> <%= job.resumes.count %> </td>
    <td> <%= job.wage_lower_bound %> </td>
    <td> <%= job.wage_upper_bound %> </td>
    <td>
          <%= link_to("Edit", edit_admin_job_path(job), :class => "btn btn-xs btn-info") %>
          <%= link_to("Destroy", admin_job_path(job), :method => :delete, :class => "btn btn-xs btn-danger", :data => { :confirm => "Are you sure?" }) %>

      <% if job.is_hidden %>

         <%= link_to("Publish", publish_admin_job_path(job) , :method => :post, :class => "btn btn-xs btn-success") %>

      <% else %>
        <%= link_to("Hide", hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-warning") %>
      <% end %>
    </td>
    <td>
      <%= job.created_at %>
    </td>
  </tr>
 <% end %>
</table>

job-listing3/app/views/admin/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for [:admin,@job] do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

job-listing3/app/views/admin/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>

</p>

job-listing3/app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Rails101
        <br>Design by Liu Dezheng

    </p>
</footer>

job-listing3/app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Job Listing3 </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                  <% if !current_user %>
                  <li><%= link_to("注册", new_user_registration_path) %> </li>
                  <li><%= link_to("登入", new_user_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">

                        <li> <%= link_to("Admin Panel", admin_jobs_path) %> </li>
                    

                        <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

job-listing3/app/views/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

job-listing3/app/views/jobs/index.html.erb
<div class="pull-right">
 <%= link_to("Add a job", new_job_path, :class => "btn btn-default" ) %>
</div>

<div class="dropdown clearfix pull-right">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuDivider" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      排序
        <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
        <li>
          <%= link_to("按照薪资下限排序", jobs_path(:order => "by_lower_bound")) %>
        </li>
        <li>
            <%= link_to("按照薪资上限排序", jobs_path(:order => "by_upper_bound")) %>

        </li>
        <li>
          <%= link_to("按照发表时间排序", jobs_path ) %>

        </li>
    </ul>
</div>


<table class="table table-boldered">
    <thead>
        <tr>
            <td>
                职缺</td>
            <td>薪资下限</td>
            <td>薪资上限</td>
            <td>刊登时间</td>
        </tr>

    </thead>
    <tbody>
        <% @jobs.each do |job| %>
        <tr>
            <td>
                <%= link_to(job.title, job_path(job)) %>
            </td>
            <td>
                <%= job.wage_lower_bound %>
            </td>
            <td>
                <%= job.wage_upper_bound %>
            </td>
            <td>
                <%= job.created_at %>
            </td>
        </tr>
        <% end %>
    </tbody>

</table>

job-listing3/app/views/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title %>
<%= f.input :description %>
<%= f.input :wage_lower_bound, :label => "薪资下限" %>
<%= f.input :wage_upper_bound, :label => "薪资上限" %>
<%= f.input :contact_email %>
<%= f.input :is_hidden %>

  <%= f.submit "Submit" %>
<% end %>

job-listing3/app/views/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>

</p>
<div class="text-center">
  <%= link_to("投交履历", new_job_resume_path(@job), :style => "font-size: 30px; text-decoration: underline;") %>
</div>

job-listing3/app/views/resumes/new.html.erb
<h3> 投交履历到 <%= @job.title %> </h3>

<hr>

<%= simple_form_for [@job, @resume] do |f| %>
  <%= f.input :content %>
  <%= f.input :attachment %>

  <%= f.submit "送出" %>
<% end %>

job-listing3/app/views/welcome/index.html.erb
<div class="jumbotron">
     <h1 class="title">Ruby 人才招聘</h1>
     <p class="slogan">Ruby 人才招聘是针对Ruby语言使用者的网站
     <br>
     期待这个你的加入。
     <br>
     相信我们Ruby人会改变世界。
     </p>
     <p class="lead"><a class="btn btn-lg btn-danger" href="/jobs">马上应聘</a></p>
   </div>


   <section id="company">
     <div class = "container-fluid">
       <div class="row">
         <div class="col-sm-4 ">
           <div class="thumbnail">
             <img src="http://fullstack-public.oss-cn-qingdao.aliyuncs.com/2017-04-15-Screenshot%20at%20Apr%2015%2021-43-31.png" alt="search" class = "img-thumbnail">
             <div class="caption">
               <h3>Around the world</h3>
             </div>
           </div>
         </div>
         <div class="col-sm-4 ">
           <div class="thumbnail">
             <img src="http://fullstack-public.oss-cn-qingdao.aliyuncs.com/2017-04-15-Screenshot%20at%20Apr%2015%2021-43-48.png" alt="bid" class = "img-thumbnail">
             <div class="caption">
               <h3>ldz201612icloud.com</h3>
             </div>
           </div>
         </div>
         <div class="col-sm-4 ">
           <div class="thumbnail">
             <img src="http://fullstack-public.oss-cn-qingdao.aliyuncs.com/2017-04-15-Screenshot%20at%20Apr%2015%2021-44-00.png" alt="heart" class = "img-thumbnail">
             <div class="caption">
               <h3>13624268361</h3>
             </div>
           </div>
         </div>
       </div>
     </div>
   </section>